### ISSUE TITLE
Latest versions (v1.2.10 and v1.2.11) break Chef 11.x compatibility

### ISSUE THREAD

**Issue by liquid-sky** [chef-cookbooks/xml#22] opened 2015-02-18 17:40 UTC
The cookbook no longer can be applied with chef 11.16.4. compile_time doesn't seem to expect any arguments. 

```
  ArgumentError
  -------------
  wrong number of arguments (1 for 0)

  Cookbook Trace:
  ---------------
    ../xml/recipes/ruby.rb:44:in `block in from_file'
    ../xml/recipes/ruby.rb:43:in `from_file'
    ../route53/recipes/default.rb:20:in `from_file'
    ../route53/recipes/route53.rb:2:in `from_file'

   43:  chef_gem 'nokogiri' do
   44>>   compile_time true if respond_to?(:compile_time)
   45:    version node['xml']['nokogiri']['version']
   46:    action :install
   47:  end
```

**Comment by lamont-granquist** [comment] 2015-02-18 23:49
You'll need to paste the whole context of the error including the stack trace.  The compile_time option doesn't exist in 11.16.4 and you should be seeing this if it actually executed that line:

```
[2015-02-18T15:37:44-08:00] FATAL: NoMethodError: undefined method `compile_time' for Chef::Resource::ChefGem
```

I can't replicate the ArgumentError exception no matter which ruby version or chef versions I've tried.

**Comment by someara** [comment] 2015-02-18 23:58
What version of Ruby are you on?
-s

**Comment by arnaud036** [comment] 2015-02-19 01:08
This is related to https://github.com/sethvargo/chef-sugar/issues/89

**Comment by sethvargo** [comment] 2015-02-19 02:04
As I said in the issue, the issue is that `respond_to?` is implicitly referring to `self`, which is a `Chef::Recipe` here. You need to change to this:

```ruby
chef_gem "nokogiri" do
  compile_time true if Chef::Resource::ChefGem.method_defined?(:compile_time)
end
```

**Comment by scalp42** [comment] 2015-02-19 07:09
https://github.com/opscode-cookbooks/aws/pull/110

**Comment by sethvargo** [comment] 2015-03-20 14:52
For the record, I have renamed the function in Chef Sugar v3.0.1 to `at_compile_time` to avoid the conflict. 

If you upgrade Chef Sugar, this should work without changes.

**Comment by jacksoncs** [comment] 2015-03-20 21:23
Could anyone help me out with this? @sethvargo 

```
 ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/krs-serverdensity/recipes/loyalty-servers.rb
  ================================================================================

  ArgumentError
  -------------
  wrong number of arguments (1 for 0)

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/serverdensity/recipes/default.rb:9:in `block in from_file'
    /var/chef/cache/cookbooks/serverdensity/recipes/default.rb:7:in `from_file'
    /var/chef/cache/cookbooks/serverdensity/recipes/alerts.rb:5:in `from_file'
    /var/chef/cache/cookbooks/krs-serverdensity/recipes/loyalty-servers.rb:20:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/serverdensity/recipes/default.rb:

    2:  # Cookbook Name:: serverdensity
    3:  # Recipe:: default
    4:
    5:  return unless node.serverdensity.enabled
    6:
    7:  chef_gem 'rest-client' do
    8:    action :install
    9>>   compile_time false if Chef::Resource::ChefGem.method_defined?(:compile_time)
   10:  end
   11:
   12:  case node[:platform]
   13:
   14:    when 'debian', 'ubuntu'
   15:      include_recipe 'apt'
   16:
   17:      apt_repository 'serverdensity' do
   18:        key 'https://www.serverdensity.com/downloads/boxedice-public.key'


  Running handlers:
[2015-03-20T15:15:21-06:00] ERROR: Running exception handlers
  Running handlers complete
[2015-03-20T15:15:21-06:00] ERROR: Exception handlers complete
[2015-03-20T15:15:21-06:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
  Chef Client failed. 1 resources updated in 29.4815188 seconds
[2015-03-20T15:15:21-06:00] ERROR: wrong number of arguments (1 for 0)
[2015-03-20T15:15:21-06:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by sethvargo** [comment] 2015-03-20 22:19
@jacksoncs upgrade to Chef Sugar latest

**Comment by jacksoncs** [comment] 2015-03-20 22:44
@sethvargo Ended up upgrading from chef-client 12.01 to 12.1.1 to fix this issue!

**Comment by tas50** [comment] 2015-10-06 05:44
Closing this out since Seth says it can be resolved by upgrading Chef Sugar

**Closed** 2015-10-06 05:44 UTC
